version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - /data
    environment:
      - POSTGRES_PASSWORD=minerva
      - POSTGRES_USER=minerva
      - POSTGRES_DB=minerva
    ports:
      - "5432:5432"
    network_mode: host