from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from email.mime.image import MIMEImage
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from ipware import get_client_ip
import smtplib
from datetime import datetime
import pytz
import time

def redirect_login(request):
    return redirect('/login')

def do_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return redirect('/app')
    else:
        all_users = User.objects.values()
        uemail = set()
        for user in all_users:
            if user['email']:
                uemail.add(user['email'])

        IST = pytz.timezone('Asia/Kolkata')
        now = datetime.now(IST)
        time_fmt = now.strftime("%d/%m/%Y %H:%M:%S %z")
        time_str="At the time " + time_fmt + " IST"

        ip_str = "from IP address: " + request.POST['ip']
        # ip, is_routable = get_client_ip(request)
        # if ip is None:
        #     ip_str = "Couldn't get client IP address"
        # else:
        #     if is_routable:
        #         ip_str = "from IP address: " + ip
        #     else:
        #         ip_str = "from private IP address: " + ip

        me="minervaprotect@gmail.com"
        me_password="abhisar1234"
        msg = MIMEMultipart()
        msg['Subject'] = "Failed Login Attempt"
        msg['From'] = me
        msg.preamble = time_str
        msg_txt = ("<html>"
                    "<head><title>Failed Login Attempt</title></head>"
                    "<body>"
                        "<h1 style=\"color:red;\">There was a failed login attempt!</h1>"
                        "<p>on time GMT: %s</p>"
                        "<p><b>using the username: %s</b></p>"
                        "<p><b>%s</b></p>"
                        "<footer>Please don't reply, this is an autogenerated mail.</footer>"
                    "</body>"
                "</html>" % (time_str, request.POST['username'], ip_str))
        msg.attach(MIMEText(msg_txt, 'html'))
        smtp_conn = smtplib.SMTP("smtp.gmail.com", port=587)
        print "connection stablished"
        smtp_conn.starttls()
        smtp_conn.ehlo_or_helo_if_needed()
        smtp_conn.login(me, me_password)
        for email in uemail:
            msg['To'] = email
            smtp_conn.sendmail(me, email, msg.as_string())
        smtp_conn.quit()
        return redirect('/login')
